### ISSUE TITLE
Windows exe location issue

### ISSUE THREAD

**Issue by zmoon** [gnikit/findent-pypi#14]
It refuses to install with pipx, saying 

> No apps associated with package findent or its dependencies. If you are attempting to install a library, pipx should not be used.
Consider using pip or a similar tool instead.

Maybe this is because the install puts the exe in `bin` instead of `Scripts`. (`pipx install findent` does work on Linux.)

**Comment by gnikit** [comment]
Yeah, I am not sure about this. I don't use `pipx` I would stick with `pip` for the time being, until I rewrite the setup.py|cfg|pyproject.toml files.

**Comment by zmoon** [comment]
It is also an issue with `pip install` in a venv. `findent` doesn't get on `PATH` since it isn't in the `Scripts` dir. Also I found the `wfindent` I got when I `pip install`ed is a sh script.

**Comment by gnikit** [comment]
Could you provide some steps to replicate this. I was unable to on Windows 10.

As for wfindent I am aware, it was a platform issue from the wfindent side of things. I think it has now been fixed so I should update the PyPi script as well.

**Comment by zmoon** [comment]
> some steps to replicate this

I am also on Windows 10, using Windows PowerShell. Here with Python 3.9:

```
python3.9 -m venv venv39
.\venv39\Scripts\activate
pip install findent
```

For me, `pip install findent` adds a `bin` dir within `venv39`. But the venv activation only adds `venv39\Scripts` to `PATH`, so `findent` isn't picked up, though `.\venv39\bin\findent.exe` still works.

**Comment by gnikit** [comment]
I think I figured out what's going on. I need to add the `scripts=[]` field on the setup wheel and findent should then be placed in scripts. I will do it today and issue a patch release.

In general tough, installing general purpose tools like CMake and findent on virtual environments does not make much sense. Isolating them from the system does not provide any benefit since they have no real python dependencies.

**Comment by zmoon** [comment]
> installing general purpose tools like CMake and findent on virtual environments does not make much sense.

One reason you might want to do this is to have a reproducible dev environment, i.e. specified fixed verisons of tools, e.g. for a collaborative project. One example is the [pre-commit](https://pre-commit.com/) framework. I [was experimenting](https://github.com/zmoon/findent-pre-commit) with different ways of offering findent as a pre-commit hook and feel findent-pypi could provide a good option (faster and perhaps leaner than the conda-forge install).

Also I wouldn't want to pollute my system Python installation just to install findent, that's why I mentioned pipx.

**Comment by gnikit** [comment]
I had a quick test with `scripts` and I don't think I can make it work without having to include an entry point through a Python script which I am trying to avoid since it increases the maintenance needed for this project. The scripts included via `scripts=[]` need to be utf-8 so the `findent` binary cannot be included directly. 

I will see if there is anything else that can be done, ideally using the new version

**Comment by zmoon** [comment]
Seems `wfindent` is not included with the new build method?
https://github.com/gnikit/findent-pypi/blob/39fccbb2bc1c93041213ef1ed40e74972e69b99e/CMakeLists.txt#L55

**Comment by zmoon** [comment]
> Seems `wfindent` is not included with the new build method?

@gnikit , whenever you get a chance, still curious to learn whether not including `wfindent` will continiue

**Comment by gnikit** [comment]
Sorry forgot to answer @zmoon, I will see what can be done about `wfindent` I am tempted to just write it in Python since the .sh/.bat scripts are at best a hack solution. I also think I did not actually fix this github issue properly... I seem to recall findent.exe still being placed under `bin/`. Could you please confirm?

**Comment by gnikit** [comment]
@zmoon Can you download the `artifacts` from here https://github.com/gnikit/findent-pypi/actions/runs/4743495272, extract them and install in a virtual environment one of the Windows wheels and tell me if findent.exe is now in the right location?

There's a bunch of wheels in the artifacts.zip, I think any wheel with the `win` word in the name should work for this test (they are all identical internally)

**Comment by zmoon** [comment]
Yep it installs it under `Scripts` 🎉

**Comment by gnikit** [comment]
Awesome, will try and get the patch + make the wheels pythonless later today and will issue a patch release.

**Comment by zmoon** [comment]
@gnikit if you could do that release when you get a chance?

**Comment by gnikit** [comment]
I am reopening this since the CMakeLists.txt config does not appear to have addressed this

**Comment by zmoon** [comment]
@gnikit why do you say that? For me, the main branch still works. Tested in a virtual env on Windows 10 just now, I get a `venv/Scripts/findent.exe`, which is on PATH when `venv` is activated.

**Comment by gnikit** [comment]
I have no idea what happened last time I tried this. It appears that I tried it in a broken Windows virtual machine and the binaries ended up in the bin/ directory instead of the Scripts/. I will close this and make a release later today.
