### ISSUE TITLE
Is there a connection between this project and https://github.com/wvermin/findent ?

### ISSUE THREAD

**Issue by Beliavsky** [gnikit/findent-pypi#32]
My guess is no, since your project is in Python and the other one is not. I will add it to my list of Fortran tools https://github.com/Beliavsky/Fortran-Tools .

**Comment by gnikit** [comment]
Hey @Beliavsky, so this project is meant to automatically generate the Python wheels for findent so that it can be installed via pip. It does not actually store any of the source code for findent. It fetches it directly from source forge when there is a new release

https://github.com/gnikit/findent-pypi/blob/09b95fb2b88cd798303b8da09f5bfcdf14a87a92/CMakeLists.txt#L29-L37

That being said, the GitHub repo you posted is a git "live-clone" from the findent author, of the subversion repo that tends to lag behind/ That's why this repo (findent-pypi) uses the sourceforge tarballs instead.

I hope that clears things up a bit.

**Comment by Beliavsky** [comment]
Thanks. I added a mention of your project in the findent entry.

**Comment by gnikit** [comment]
Hey @Beliavsky I am turning this into a Discussion, feel free to ask any more questions.
